version: '2'
services:
    zelda1:
        build:
            context: .
            args:
                deploy: 1
        volumes:
            - /www/zelda:/www/zelda
        ports:
            - 2000:2000
            - 8000:8000
    zelda2:
        build:
            context: .
            args:
                deploy: 1
        volumes:
            - /www/zelda:/www/zelda
        ports:
            - 2001:2000
            - 8001:8000
