version: '2'
services:
    zelda:
        build:
            context: .
            args:
                deploy: 1
        volumes:
            - /www/zelda:/www/zelda
        ports:
            - 2000:2000
